image: node:alpine
# Command to start on workspace startup (optional)
tasks:
  - name: Start Client
  init: |
  cd client && npm install
  command: |
  npm start
  -name: Start Server
  init: |
  cd server && npm install
  command: |
  npm run dev
  
# Ports to expose on workspace startup (optional)
ports:
  - port: 3000
  - port: 4000
