version: "3.9"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "443:3000"
      
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"